Use both JCSDA and UKMO environments for CI build

diff --git a/ci/build-and-test b/ci/build-and-test
--- a/ci/build-and-test
+++ b/ci/build-and-test
@@ -1,5 +1,8 @@
 #!/bin/bash
-set -euo pipefail
+#
+# (C) Crown Copyright 2023, the Met Office. All rights reserved.
+#
+set -euxo pipefail
 
 finally() {
     trap '' ERR
@@ -14,29 +17,33 @@ HERE="$(cd "$(dirname "$0")" && pwd)"
 THIS="$(basename "$0")"
 NPROC=${NPROC:-$(nproc)}
 WORKD="$(mktemp -d "${THIS}-XXXXXX" -t)"
+GENERATOR=Unix\ Makefiles
+if command -v ninja &>/dev/null; then GENERATOR=Ninja; fi
 
-trap finally ERR
-trap finally EXIT
+trap finally ERR EXIT
 
 cd "${WORKD}"
 
-GENERATOR=Unix\ Makefiles
-if command -v ninja; then GENERATOR=Ninja; fi
+# If using JCSDA Docker container
+if [[ -f /opt/spack-environment/activate.sh ]]; then
+    source /opt/spack-environment/activate.sh
+fi
 
 # -- Configure
-(   set -x;
-    cmake -B . -S "${HERE}" -G "$GENERATOR" \
+cmake -B . -S "${HERE}" -G "${GENERATOR}" \
     -DCMAKE_BUILD_TYPE=Debug \
     -DMPI_ARGS="--oversubscribe"
 
-
 # -- Build
-    cmake --build . -j "${NPROC}"
-
+cmake --build . -j "${NPROC}"
 
 # -- Test
-    env OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
-    ctest -j "$NPROC" -R "coding_norms" --output-on-failure
-)
+env OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
+    ctest -j"${NPROC}" --test-dir './monio'
+
+# env OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
+#     ctest -j"${NPROC}" --test-dir './monio' --output-on-failure ||\
+# env OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
+#     ctest --test-dir './monio' --rerun-failed -V
 
 exit
